export const RASGOS_PERSONALIDAD = {
  positivos: [
    "amable",
    "valiente",
    "creativo",
    "determinado",
    "empático",
    "generoso",
    "honesto",
    "optimista",
    "paciente",
    "sabio",
  ],
  negativos: [
    "ansioso",
    "arrogante",
    "cobarde",
    "egoísta",
    "impaciente",
    "pesimista",
    "terco",
    "vengativo",
    "celoso",
    "inseguro",
  ],
  neutros: [
    "introvertido",
    "extrovertido",
    "meticuloso",
    "espontáneo",
    "tradicional",
    "moderno",
    "práctico",
    "soñador",
    "reservado",
  ],
};

export const OCUPACIONES_POR_EPOCA = {
  historica: [
    "herrero",
    "escriba",
    "comerciante",
    "agricultor",
    "artesano",
    "soldado",
    "curandero",
    "marinero",
    "constructor",
    "pastor",
  ],
  moderna: [
    "médico",
    "profesor",
    "ingeniero",
    "periodista",
    "abogado",
    "contador",
    "enfermero",
    "arquitecto",
    "músico",
    "escritor",
  ],
  contemporanea: [
    "desarrollador",
    "diseñador UX",
    "influencer",
    "data scientist",
    "emprendedor",
    "consultor",
    "community manager",
    "bartender",
  ],
};

export const MOODS_DIARIO = [
  "melancólico",
  "esperanzado",
  "ansioso",
  "reflexivo",
  "nostálgico",
  "agradecido",
  "frustrado",
  "emocionado",
  "confundido",
  "sereno",
];
